var test = [
    'BEGIN:VCARD',
    'VERSION',
    '4.0',
    'N',
    'Gump;Forrest',
    'ORG',
    'Bubba Gump Shrimp Co.',
    'TITLE',
    'Shrimp Man',
    'TEL',
    'TYPE=work,voice',
    'VALUE=uri',
    'tel',
    '+33145789654',
    'TEL',
    'TYPE=cell,voice',
    'VALUE=uri',
    'tel',
    '+33612457896',
    'EMAIL',
    'forrestgump@example.com',
    'REV',
    '20080424T195243Z',
    'END:VCARD'
];
